// Generated Neuro Graph business-process sidebar

export const businessProcessSidebar = [
  { text: 'Overview', link: '/business-processes/README' },
  {
    text: 'Customer & Revenue',
    collapsed: true,
    items: [
      { text: 'BP-001 Lead Capture to Qualification', link: '/business-processes/lead-capture-to-qualification' },
      { text: 'BP-002 Campaign to Lead', link: '/business-processes/campaign-to-lead' },
      { text: 'BP-003 Opportunity to Quote', link: '/business-processes/opportunity-to-quote' },
      { text: 'BP-004 Quote to Order', link: '/business-processes/quote-to-order' },
      { text: 'BP-005 Contract to Renewal', link: '/business-processes/contract-to-renewal' },
      { text: 'BP-006 Order Capture to Confirmation', link: '/business-processes/order-capture-to-confirmation' },
      { text: 'BP-007 Order to Delivery', link: '/business-processes/order-to-delivery' },
      { text: 'BP-008 Delivery to Billing', link: '/business-processes/delivery-to-billing' },
      { text: 'BP-009 Billing to Cash', link: '/business-processes/billing-to-cash' },
      { text: 'BP-010 Customer Return to Credit', link: '/business-processes/customer-return-to-credit' },
      { text: 'BP-011 Complaint to Resolution', link: '/business-processes/complaint-to-resolution' },
      { text: 'BP-012 Service Request to Closure', link: '/business-processes/service-request-to-closure' },
      { text: 'BP-013 Subscription Activation to Renewal', link: '/business-processes/subscription-activation-to-renewal' },
      { text: 'BP-014 Usage Capture to Billing', link: '/business-processes/usage-capture-to-billing' },
      { text: 'BP-015 Partner Channel Order to Settlement', link: '/business-processes/partner-channel-order-to-settlement' },
      { text: 'BP-016 Customer Onboarding to Account Activation', link: '/business-processes/customer-onboarding-to-account-activation' },
      { text: 'BP-017 Credit Check to Order Release', link: '/business-processes/credit-check-to-order-release' },
      { text: 'BP-018 Price Determination to Approval', link: '/business-processes/price-determination-to-approval' },
    ]
  },
  {
    text: 'Procurement & Supplier',
    collapsed: true,
    items: [
      { text: 'BP-019 Supplier Discovery to Qualification', link: '/business-processes/supplier-discovery-to-qualification' },
      { text: 'BP-020 Supplier Onboarding to Activation', link: '/business-processes/supplier-onboarding-to-activation' },
      { text: 'BP-021 Source to Contract', link: '/business-processes/source-to-contract' },
      { text: 'BP-022 Contract to Purchase Requisition', link: '/business-processes/contract-to-purchase-requisition' },
      { text: 'BP-023 Purchase Requisition to Purchase Order', link: '/business-processes/purchase-requisition-to-purchase-order' },
      { text: 'BP-024 Purchase Order to Confirmation', link: '/business-processes/purchase-order-to-confirmation' },
      { text: 'BP-025 Purchase Order to Goods Receipt', link: '/business-processes/purchase-order-to-goods-receipt' },
      { text: 'BP-026 Goods Receipt to Supplier Invoice', link: '/business-processes/goods-receipt-to-supplier-invoice' },
      { text: 'BP-027 Supplier Invoice to Payment', link: '/business-processes/supplier-invoice-to-payment' },
      { text: 'BP-028 Three Way Match to Exception Resolution', link: '/business-processes/three-way-match-to-exception-resolution' },
      { text: 'BP-029 Supplier Return to Credit Memo', link: '/business-processes/supplier-return-to-credit-memo' },
      { text: 'BP-030 Spend Request to Approval', link: '/business-processes/spend-request-to-approval' },
      { text: 'BP-031 Catalog Request to Order', link: '/business-processes/catalog-request-to-order' },
      { text: 'BP-032 Supplier Performance Review to Improvement', link: '/business-processes/supplier-performance-review-to-improvement' },
      { text: 'BP-033 Contract Compliance to Exception', link: '/business-processes/contract-compliance-to-exception' },
      { text: 'BP-034 Import Procurement to Landed Cost', link: '/business-processes/import-procurement-to-landed-cost' },
      { text: 'BP-035 Service Entry to Invoice', link: '/business-processes/service-entry-to-invoice' },
      { text: 'BP-036 Procurement Closure to Archive', link: '/business-processes/procurement-closure-to-archive' },
    ]
  },
  {
    text: 'Inventory & Logistics',
    collapsed: true,
    items: [
      { text: 'BP-037 Material Request to Reservation', link: '/business-processes/material-request-to-reservation' },
      { text: 'BP-038 Inbound Delivery to Putaway', link: '/business-processes/inbound-delivery-to-putaway' },
      { text: 'BP-039 Outbound Delivery to Goods Issue', link: '/business-processes/outbound-delivery-to-goods-issue' },
      { text: 'BP-040 Stock Transfer Request to Receipt', link: '/business-processes/stock-transfer-request-to-receipt' },
      { text: 'BP-041 Goods Movement to Inventory Posting', link: '/business-processes/goods-movement-to-inventory-posting' },
      { text: 'BP-042 Cycle Count to Adjustment', link: '/business-processes/cycle-count-to-adjustment' },
      { text: 'BP-043 Physical Inventory to Reconciliation', link: '/business-processes/physical-inventory-to-reconciliation' },
      { text: 'BP-044 Batch Creation to Traceability', link: '/business-processes/batch-creation-to-traceability' },
      { text: 'BP-045 Serial Number Assignment to Tracking', link: '/business-processes/serial-number-assignment-to-tracking' },
      { text: 'BP-046 Warehouse Task to Confirmation', link: '/business-processes/warehouse-task-to-confirmation' },
      { text: 'BP-047 Picking to Packing', link: '/business-processes/picking-to-packing' },
      { text: 'BP-048 Packing to Shipment', link: '/business-processes/packing-to-shipment' },
      { text: 'BP-049 Shipment Planning to Dispatch', link: '/business-processes/shipment-planning-to-dispatch' },
      { text: 'BP-050 Transportation Tender to Carrier Confirmation', link: '/business-processes/transportation-tender-to-carrier-confirmation' },
      { text: 'BP-051 Freight Cost Capture to Settlement', link: '/business-processes/freight-cost-capture-to-settlement' },
      { text: 'BP-052 Return Receipt to Restock', link: '/business-processes/return-receipt-to-restock' },
      { text: 'BP-053 Scrap Request to Inventory Writeoff', link: '/business-processes/scrap-request-to-inventory-writeoff' },
      { text: 'BP-054 Inventory Aging to Disposition', link: '/business-processes/inventory-aging-to-disposition' },
    ]
  },
  {
    text: 'Manufacturing & Operations',
    collapsed: true,
    items: [
      { text: 'BP-055 Demand Signal to Production Plan', link: '/business-processes/demand-signal-to-production-plan' },
      { text: 'BP-056 Production Order Creation to Release', link: '/business-processes/production-order-creation-to-release' },
      { text: 'BP-057 Production Order Release to Staging', link: '/business-processes/production-order-release-to-staging' },
      { text: 'BP-058 Material Staging to Consumption', link: '/business-processes/material-staging-to-consumption' },
      { text: 'BP-059 Operation Confirmation to Yield', link: '/business-processes/operation-confirmation-to-yield' },
      { text: 'BP-060 Quality Inspection to Usage Decision', link: '/business-processes/quality-inspection-to-usage-decision' },
      { text: 'BP-061 Production Variance to Settlement', link: '/business-processes/production-variance-to-settlement' },
      { text: 'BP-062 Make to Stock Production', link: '/business-processes/make-to-stock-production' },
      { text: 'BP-063 Make to Order Production', link: '/business-processes/make-to-order-production' },
      { text: 'BP-064 Engineer to Order Fulfillment', link: '/business-processes/engineer-to-order-fulfillment' },
      { text: 'BP-065 Bill of Material Change to Release', link: '/business-processes/bill-of-material-change-to-release' },
      { text: 'BP-066 Routing Change to Production Version', link: '/business-processes/routing-change-to-production-version' },
      { text: 'BP-067 Work Center Capacity to Dispatch', link: '/business-processes/work-center-capacity-to-dispatch' },
      { text: 'BP-068 Shop Floor Issue to Resolution', link: '/business-processes/shop-floor-issue-to-resolution' },
      { text: 'BP-069 Rework Order to Completion', link: '/business-processes/rework-order-to-completion' },
      { text: 'BP-070 Subcontracting Issue to Receipt', link: '/business-processes/subcontracting-issue-to-receipt' },
      { text: 'BP-071 Co Product Allocation to Costing', link: '/business-processes/co-product-allocation-to-costing' },
      { text: 'BP-072 Production Close to Archive', link: '/business-processes/production-close-to-archive' },
    ]
  },
  {
    text: 'Finance & Controlling',
    collapsed: true,
    items: [
      { text: 'BP-073 Journal Entry Request to Posting', link: '/business-processes/journal-entry-request-to-posting' },
      { text: 'BP-074 Accrual Calculation to Reversal', link: '/business-processes/accrual-calculation-to-reversal' },
      { text: 'BP-075 Accounts Payable Invoice to Clearing', link: '/business-processes/accounts-payable-invoice-to-clearing' },
      { text: 'BP-076 Accounts Receivable Invoice to Clearing', link: '/business-processes/accounts-receivable-invoice-to-clearing' },
      { text: 'BP-077 Incoming Payment to Bank Reconciliation', link: '/business-processes/incoming-payment-to-bank-reconciliation' },
      { text: 'BP-078 Outgoing Payment to Bank Statement', link: '/business-processes/outgoing-payment-to-bank-statement' },
      { text: 'BP-079 Bank Statement to Cash Application', link: '/business-processes/bank-statement-to-cash-application' },
      { text: 'BP-080 Expense Claim to Reimbursement', link: '/business-processes/expense-claim-to-reimbursement' },
      { text: 'BP-081 Cost Center Planning to Allocation', link: '/business-processes/cost-center-planning-to-allocation' },
      { text: 'BP-082 Profit Center Posting to Reporting', link: '/business-processes/profit-center-posting-to-reporting' },
      { text: 'BP-083 Internal Order Planning to Settlement', link: '/business-processes/internal-order-planning-to-settlement' },
      { text: 'BP-084 Asset Acquisition to Capitalization', link: '/business-processes/asset-acquisition-to-capitalization' },
      { text: 'BP-085 Asset Depreciation to Posting', link: '/business-processes/asset-depreciation-to-posting' },
      { text: 'BP-086 Asset Transfer to Retirement', link: '/business-processes/asset-transfer-to-retirement' },
      { text: 'BP-087 Budget Request to Release', link: '/business-processes/budget-request-to-release' },
      { text: 'BP-088 Commitment Tracking to Actuals', link: '/business-processes/commitment-tracking-to-actuals' },
      { text: 'BP-089 Period Close to Financial Statement', link: '/business-processes/period-close-to-financial-statement' },
      { text: 'BP-090 Intercompany Transaction to Reconciliation', link: '/business-processes/intercompany-transaction-to-reconciliation' },
      { text: 'BP-091 Tax Determination to Reporting', link: '/business-processes/tax-determination-to-reporting' },
      { text: 'BP-092 Currency Revaluation to Posting', link: '/business-processes/currency-revaluation-to-posting' },
    ]
  },
  {
    text: 'Assets & Maintenance',
    collapsed: true,
    items: [
      { text: 'BP-093 Maintenance Request to Notification', link: '/business-processes/maintenance-request-to-notification' },
      { text: 'BP-094 Notification to Work Order', link: '/business-processes/notification-to-work-order' },
      { text: 'BP-095 Work Order Planning to Release', link: '/business-processes/work-order-planning-to-release' },
      { text: 'BP-096 Work Order Execution to Confirmation', link: '/business-processes/work-order-execution-to-confirmation' },
      { text: 'BP-097 Spare Part Reservation to Issue', link: '/business-processes/spare-part-reservation-to-issue' },
      { text: 'BP-098 Breakdown Event to Restoration', link: '/business-processes/breakdown-event-to-restoration' },
      { text: 'BP-099 Preventive Maintenance Plan to Call', link: '/business-processes/preventive-maintenance-plan-to-call' },
      { text: 'BP-100 Inspection Finding to Corrective Action', link: '/business-processes/inspection-finding-to-corrective-action' },
      { text: 'BP-101 Meter Reading to Maintenance Trigger', link: '/business-processes/meter-reading-to-maintenance-trigger' },
      { text: 'BP-102 Maintenance Cost Capture to Settlement', link: '/business-processes/maintenance-cost-capture-to-settlement' },
      { text: 'BP-103 Asset Warranty Claim to Recovery', link: '/business-processes/asset-warranty-claim-to-recovery' },
      { text: 'BP-104 Equipment Installation to Decommissioning', link: '/business-processes/equipment-installation-to-decommissioning' },
    ]
  },
  {
    text: 'Projects & Services',
    collapsed: true,
    items: [
      { text: 'BP-105 Project Proposal to Approval', link: '/business-processes/project-proposal-to-approval' },
      { text: 'BP-106 Project Planning to Baseline', link: '/business-processes/project-planning-to-baseline' },
      { text: 'BP-107 Work Package Assignment to Execution', link: '/business-processes/work-package-assignment-to-execution' },
      { text: 'BP-108 Timesheet Capture to Approval', link: '/business-processes/timesheet-capture-to-approval' },
      { text: 'BP-109 Milestone Completion to Billing', link: '/business-processes/milestone-completion-to-billing' },
      { text: 'BP-110 Service Contract to Service Order', link: '/business-processes/service-contract-to-service-order' },
      { text: 'BP-111 Service Order to Dispatch', link: '/business-processes/service-order-to-dispatch' },
      { text: 'BP-112 Service Delivery to Confirmation', link: '/business-processes/service-delivery-to-confirmation' },
      { text: 'BP-113 Service Confirmation to Billing', link: '/business-processes/service-confirmation-to-billing' },
      { text: 'BP-114 Project Cost Capture to Settlement', link: '/business-processes/project-cost-capture-to-settlement' },
      { text: 'BP-115 Change Request to Scope Update', link: '/business-processes/change-request-to-scope-update' },
      { text: 'BP-116 Project Closure to Lessons Learned', link: '/business-processes/project-closure-to-lessons-learned' },
    ]
  },
  {
    text: 'Workforce & HR',
    collapsed: true,
    items: [
      { text: 'BP-117 Workforce Request to Job Requisition', link: '/business-processes/workforce-request-to-job-requisition' },
      { text: 'BP-118 Candidate Application to Screening', link: '/business-processes/candidate-application-to-screening' },
      { text: 'BP-119 Interview Scheduling to Feedback', link: '/business-processes/interview-scheduling-to-feedback' },
      { text: 'BP-120 Offer Creation to Acceptance', link: '/business-processes/offer-creation-to-acceptance' },
      { text: 'BP-121 Employee Onboarding to Activation', link: '/business-processes/employee-onboarding-to-activation' },
      { text: 'BP-122 Employee Master Data Change to Approval', link: '/business-processes/employee-master-data-change-to-approval' },
      { text: 'BP-123 Time Recording to Approval', link: '/business-processes/time-recording-to-approval' },
      { text: 'BP-124 Leave Request to Approval', link: '/business-processes/leave-request-to-approval' },
      { text: 'BP-125 Payroll Preparation to Payment', link: '/business-processes/payroll-preparation-to-payment' },
      { text: 'BP-126 Performance Goal Setting to Review', link: '/business-processes/performance-goal-setting-to-review' },
      { text: 'BP-127 Learning Assignment to Completion', link: '/business-processes/learning-assignment-to-completion' },
      { text: 'BP-128 Employee Offboarding to Deactivation', link: '/business-processes/employee-offboarding-to-deactivation' },
    ]
  },
  {
    text: 'Planning & Supply Chain',
    collapsed: true,
    items: [
      { text: 'BP-129 Strategic Plan to Demand Forecast', link: '/business-processes/strategic-plan-to-demand-forecast' },
      { text: 'BP-130 Demand Forecast to Supply Plan', link: '/business-processes/demand-forecast-to-supply-plan' },
      { text: 'BP-131 Supply Plan to Procurement Proposal', link: '/business-processes/supply-plan-to-procurement-proposal' },
      { text: 'BP-132 Supply Plan to Production Proposal', link: '/business-processes/supply-plan-to-production-proposal' },
      { text: 'BP-133 Sales and Operations Planning Cycle', link: '/business-processes/sales-and-operations-planning-cycle' },
      { text: 'BP-134 Material Requirements Planning to Exception', link: '/business-processes/material-requirements-planning-to-exception' },
      { text: 'BP-135 Replenishment Proposal to Order', link: '/business-processes/replenishment-proposal-to-order' },
      { text: 'BP-136 Allocation Planning to Fulfillment', link: '/business-processes/allocation-planning-to-fulfillment' },
      { text: 'BP-137 Capacity Planning to Constraint Resolution', link: '/business-processes/capacity-planning-to-constraint-resolution' },
      { text: 'BP-138 Scenario Planning to Decision', link: '/business-processes/scenario-planning-to-decision' },
      { text: 'BP-139 Forecast Consumption to Rebalance', link: '/business-processes/forecast-consumption-to-rebalance' },
      { text: 'BP-140 Supply Chain Exception to Recovery', link: '/business-processes/supply-chain-exception-to-recovery' },
    ]
  },
  {
    text: 'Governance Risk Data',
    collapsed: true,
    items: [
      { text: 'BP-141 Policy Draft to Publication', link: '/business-processes/policy-draft-to-publication' },
      { text: 'BP-142 Control Design to Test', link: '/business-processes/control-design-to-test' },
      { text: 'BP-143 Risk Identification to Mitigation', link: '/business-processes/risk-identification-to-mitigation' },
      { text: 'BP-144 Audit Finding to Remediation', link: '/business-processes/audit-finding-to-remediation' },
      { text: 'BP-145 Access Request to Approval', link: '/business-processes/access-request-to-approval' },
      { text: 'BP-146 Role Design to Assignment', link: '/business-processes/role-design-to-assignment' },
      { text: 'BP-147 Master Data Request to Approval', link: '/business-processes/master-data-request-to-approval' },
      { text: 'BP-148 Data Quality Issue to Correction', link: '/business-processes/data-quality-issue-to-correction' },
      { text: 'BP-149 Integration Event to Error Resolution', link: '/business-processes/integration-event-to-error-resolution' },
      { text: 'BP-150 Change Request to Production Release', link: '/business-processes/change-request-to-production-release' },
    ]
  },
]
